LUMC/pytest-workflow

README.md

Update the documentation so users can start to use it.

---

HISTORY.md
src/pytest_workflow/plugin.py
src/pytest_workflow/workflow.py
tests/test_success_messages.py

Save stdout and stderr to files and report it to stdout of pytest.

---

HISTORY.rst
src/pytest_workflow/plugin.py
src/pytest_workflow/workflow.py
tests/test_success_messages.py

Also added a few tests that make sure that pytest crashes do not longer go unnoticed.
EDIT: Also took the opportunity to make the log structure better.

Fix error messages when running multiple workflows

---

.travis.yml

do after success only in python3.5

---

.pylintrc
HISTORY.rst
src/pytest_workflow/content_tests.py
src/pytest_workflow/plugin.py
tests/test_fail_messages.py

Better error messages when file that is not created is checked for content, and better workflow exit code messages.

---

README.rst

This adds the version of our package on the readme as well as the supported python versions.

pypi version more prominent on readme

---

HISTORY.rst
README.rst
docs/running_pytest_workflow.rst
src/pytest_workflow/plugin.py
tests/test_temp_directory.py

add --kwd flag and notify user of directory deletion

---

.github/release_checklist.md
HISTORY.rst
README.rst
docs/installation.rst
setup.py

I also did some housekeeping work. Improve the release procedure, add another qualifier and added new shields on the homepage.

Add information on how to install on conda.

---

.pylintrc
HISTORY.rst
src/pytest_workflow/plugin.py
src/pytest_workflow/schema.py
src/pytest_workflow/schema/schema.json
src/pytest_workflow/workflow.py
tests/test_threading_errors.py
tests/test_workflow_dependent_tests.py

Fix error with dangling threads after errors

---

.pylintrc
HISTORY.rst
setup.py
src/pytest_workflow/plugin.py
src/pytest_workflow/schema.py
src/pytest_workflow/schema/schema.json
src/pytest_workflow/workflow.py
tests/test_threading_errors.py
tests/test_workflow_dependent_tests.py

Release 1.1.2

---

HISTORY.rst
docs/examples.rst
tests/functional/simple_wdl_test_cases.yml
tests/functional/test_cromwell.py
tests/pipelines/wdl/simple.json
tests/pipelines/wdl/simple.options.json
tests/pipelines/wdl/simple.wdl

This update was possible because of the updates to Cromwell version 40.
Also updated the test wdl to reflect the snakemake test pipeline in the repo.

Update documentation for Cromwell + WDL tests.

---

HISTORY.rst
docs/installation.rst
docs/running_pytest_workflow.rst
docs/writing_tests.rst
pytest.ini
src/pytest_workflow/plugin.py
tests/test_miscellaneous_crashes.py

Crash when multiple pipelines have the same name.

---

.travis.yml
HISTORY.rst
MANIFEST.in
docs/writing_tests.rst
setup.cfg
setup.py
tox.ini

Add some tags for discoverability.
Includes a documentation fix.

Discoverability

---

.travis.yml
HISTORY.rst
MANIFEST.in
docs/installation.rst
docs/running_pytest_workflow.rst
docs/writing_tests.rst
pytest.ini
setup.cfg
setup.py
src/pytest_workflow/plugin.py
tests/test_miscellaneous_crashes.py
tox.ini

Release 1.2.2

---

HISTORY.rst
docs/examples.rst
docs/installation.rst
docs/running_pytest_workflow.rst
docs/writing_tests.rst
src/pytest_workflow/plugin.py

Mostly punctuation. Cromwell now creates directories that can be deleted by the user, so the $EUID workaround is removed from the docs.
Also updated the specific test example to make better use of pathlib.

Slight documentation improvements.

---

.travis.yml
HISTORY.rst
setup.py
src/pytest_workflow/__init__.py
src/pytest_workflow/plugin.py
src/pytest_workflow/schema.py
src/pytest_workflow/util.py
tests/functional/simple_snakefile_test_cases.yml
tests/functional/test_cromwell.py
tests/functional/test_snakemake.py
tests/test_utils.py

Fix incorrect evaluation of subdirectories

---

HISTORY.rst
setup.py
src/pytest_workflow/content_tests.py
src/pytest_workflow/plugin.py
tests/test_warnings.py

Fix deprecation warnings

---

HISTORY.rst
src/pytest_workflow/plugin.py
tests/test_workflow_dependent_tests.py

Deprecate use of name in workflow marks

---

HISTORY.rst
README.rst
docs/installation.rst
docs/known_issues.rst
docs/writing_tests.rst
setup.py
src/pytest_workflow/content_tests.py
src/pytest_workflow/file_tests.py
src/pytest_workflow/plugin.py
src/pytest_workflow/schema.py
src/pytest_workflow/schema/schema.json
tests/test_content_functions.py
tests/test_fail_messages.py
tests/test_schema.py
tests/test_success_messages.py
tests/test_workflow_dependent_tests.py
tests/yamls/valid/regex_file.yaml

Release 1.4.0

---

setup.py
src/pytest_workflow/schema.py
src/pytest_workflow/util.py
tests/functional/test_functional.py
tests/test_content_functions.py
tests/test_file_functions.py
tests/test_schema.py
tests/test_success_messages.py
tests/test_temp_directory.py
tests/test_utils.py
tests/test_workflow_dependent_tests.py

Changes are not going to be in the changelog as this is minor and also not user facing.

Improve code readability by making better use of pathlib.

---

.travis.yml

Use newest version of cromwell in testing.

---

.github/workflows/ci.yml
HISTORY.rst
README.rst
docs/examples.rst
docs/installation.rst
docs/running_pytest_workflow.rst
pyproject.toml
setup.py
src/pytest_workflow/plugin.py
src/pytest_workflow/util.py
tests/functional/simple_snakefile_test_cases.yml
tests/functional/simple_wdl_test_cases.yml
tests/test_utils.py
tests/test_warnings.py
tox.ini

Release 1.6.0

---

HISTORY.rst
src/pytest_workflow/util.py
tests/functional/simple_snakefile_test_cases.yml
tests/test_utils.py

Throw an error when files checked in in git are not found.

---

HISTORY.rst
docs/conf.py
docs/writing_tests.rst

Document the use of environment variables with pytest-workflow

---

docs/examples.rst
tests/functional/simple_nextflow_test_cases.yml
tests/pipelines/nextflow/nextflow_testpipeline.nf

Nextflow test documentation2

---

HISTORY.rst
docs/running_pytest_workflow.rst

Document using pytest.ini

---

.github/workflows/ci.yml
HISTORY.rst
setup.py

Enable tests on python 3.11

---

.github/workflows/ci.yml
HISTORY.rst
src/pytest_workflow/util.py
tests/test_utils.py

Add a check if all submodules are present and cloned.

---

src/pytest_workflow/plugin.py

These were used for typing purposes only. Which made development easier. Since _pytest modules are not part of the public API, changes may occur.
Since 7.0.0 all necessary objects are exposed trough the API so we can import them directly.
No need to update the history for this change.

Remove underscore imports

---

.github/workflows/ci.yml
HISTORY.rst
README.rst
docs/installation.rst
docs/known_issues.rst
docs/writing_tests.rst
setup.py

Drop python 3.6 support

---

HISTORY.rst
docs/running_pytest_workflow.rst

docs:  pytest flags -k and -m are not supported

---

HISTORY.rst
README.rst
docs/writing_tests.rst
src/pytest_workflow/content_tests.py
src/pytest_workflow/schema.py
src/pytest_workflow/schema/schema.json
tests/test_content_functions.py
tests/test_encodings.py
tests/yamls/valid/dream_file.yaml
tox.ini

Add an encoding key to the YAML. Only open and read files once at maximum.

---

HISTORY.rst
src/pytest_workflow/util.py
tests/test_utils.py

Fix symlinks to directories fail when copying with --git-aware flag.

---

.github/workflows/ci.yml
tests/pipelines/nextflow/nextflow_testpipeline.nf

Functional tests for nextflow

---

.github/workflows/ci.yml
HISTORY.rst
setup.py
src/pytest_workflow/plugin.py
src/pytest_workflow/util.py
tests/pipelines/nextflow/nextflow_testpipeline.nf
tests/test_miscellaneous_crashes.py
tests/test_utils.py

Release 2.0.1
