src/pytest_workflow/plugin.py, src/pytest_workflow/schema.py, src/pytest_workflow/schema/schema.json, src/pytest_workflow/workflow.py, src/pytest_workflow/workflow_file_tests.py, tests/test_schema.py, tests/test_workflow.py, tests/workflow_tests/test_simple_echo.yml, tests/yamls/valid/dream_file.yaml, tests/yamls/valid/valid_test.yml
Rewrote the schema for pytest_workflow to match `dream_file.yaml`'s schema. This was discussed in a meeting for workflow testing requirements.
I changed the structure. In `schema.py` the schema is now parsed in a `WorkflowTest` class which has members that resemble the schema. Also sane defaults are set here. This prevents the input yamls from being parsed troughout the pytest-workflow code base. It happens in one place now. Also the named members are presumably more informative than dict().get whatever statements.
=> Rework the schema as discussed.

.pylintrc, HISTORY.md, requirements-dev.txt, requirements.txt, src/pytest_workflow/content_tests.py, src/pytest_workflow/file_tests.py, src/pytest_workflow/plugin.py, src/pytest_workflow/schema.py, src/pytest_workflow/workflow.py, tests/conftest.py, tests/test_content_functions.py, tests/test_file_functions.py, tests/test_schema.py, tox.ini
Enable static code analysis by pylint and bandit. This should catch issues before they are noticed by codacy. Also it should make us less dependent on codacy. Furthermore it allows local analysis of the code base.
=> Integrate static code analysis.

HISTORY.md, README.md, src/pytest_workflow/plugin.py, tests/test_success_messages.py, tests/test_temp_directory.py
This fixes #3 and #16 
`--basetemp` is a pytest build in that is conveniently reused here.
`--keep-workflow-wd` was the best flag name I could come up with. Suggestions are welcome.
=> Allow to change temporary directory using `--basetemp`, cleanup directories afterwards, and add `--keep-workflow-wd` flag to disable cleanup. 

requirements-docs.txt, tox.ini
Readthedocs can install a package using python setup.py install. So
it is no longer necessary to include . in the requirements for docs.
Also the tox environment can be simplified by making this change
~~- [ ] Pull request details were added to HISTORY.rst~~
=> remove redundant lines in tox and requirements-doc.txt

HISTORY.rst, docs/manual.rst, src/pytest_workflow/plugin.py, src/pytest_workflow/schema.py, src/pytest_workflow/schema/schema.json, tests/test_markers.py, tests/test_schema.py, tests/test_tags.py, tests/yamls/valid/dream_file.yaml
This will make it easier to get functional tests and integration tests separated and run individual workflows without depending on file and folder structure to accomplish these things.
=> Add `--tag` flag for easier workflow selection.

HISTORY.rst, setup.py, src/pytest_workflow/schema/schema.json, src/pytest_workflow/workflow.py, tests/test_schema.py, tests/test_workflow.py
Running an empty string as command causes pytest-workflow to hang. 
This bug was not investigated. Empty commands are nonsensical anyway, so they are now disallowed in the schema and in the workflow object.
I also disallowed empty names.
=> Empty names and commands should not be accepted as this causes bugs

HISTORY.rst, src/pytest_workflow/plugin.py
When `basetemp` was not set workflows were scattered over different temp directories in each pytest run.
Now only one workflow temp folder per pytest run is created.
=> fixed temporary folder location

HISTORY.rst, src/pytest_workflow/content_tests.py, src/pytest_workflow/file_tests.py, src/pytest_workflow/plugin.py, tests/test_fail_messages.py
When tests failed previously checking content in files it would report: 'some string' not found in content.
Now it reports: 'some string' not found in path/to/file.
Also 'some string not found in stdout
was changed to 'some string' not found in 'name of workflow': stdout.
So now if content checks fail the message is much more informative.
=> More informative failing of content tests

HISTORY.rst, README.rst, docs/running_pytest_workflow.rst, src/pytest_workflow/content_tests.py, src/pytest_workflow/file_tests.py, src/pytest_workflow/plugin.py, src/pytest_workflow/workflow.py, tests/test_temp_directory.py, tests/test_workflow.py
This streams the logs to a file. This means the progress of a running workflow can be checked by running `tail -f` on the stdout and stderr file. This is very useful when testing workflow. 
This uses _less_ code. The location of the stdout and stderr are now always reported when the workflow is started. This removes some logic from the code. Stdout and stderr are files now, which means their content can be tested just like other files, this allows reuse of code, and removal of log specific code.
EDIT: I realized that we had a lock in place because the wait command did not only wait, it also wrote the stderr and stdout to the object variables. Since that functionality is not necessary anymore, the wait command now only waits. This means the locks can be dropped and things can be much …
=> Stream logs to files.

.travis.yml, HISTORY.rst, README.rst, docs/writing_tests.rst, mypy.ini, src/pytest_workflow/content_tests.py, src/pytest_workflow/plugin.py, src/pytest_workflow/workflow.py, tests/test_workflow_dependent_tests.py, tox.ini
Based on design in issue #56 .
+ Custom test syntax was added
+ Custom test syntax explained in the docs
+ Custom test syntax extensively tested
+ Apparently a `mypy` update caused our mypy linting to crash. It appears the way mypy was invoked was wrong all this time. This is now fixed.
+ Temporary workflow directories are not deleted until just before pytest exits. This allows all custom tests to run on workflow directories.
+ Apparently the conda/cromwell/tox/pip/pytest combination was not working correctly. Installing tox via cromwell fixed the issue, but it took me a while to debug this.
=> Enable custom tests on workflow runs.

HISTORY.rst, docs/running_pytest_workflow.rst, src/pytest_workflow/plugin.py, tests/test_temp_directory.py
Unfortunately it is not possible to do this the elegant way: only keep directories for workflows that have failing tests. Pytest does not provide functionality for that. 
So the algorithm is quite simple. Most of the lines of code are tests and documentation.
Fixes #69
=> Add flag for disabling cleanup when tests fail.

HISTORY.rst, src/pytest_workflow/__init__.py, src/pytest_workflow/plugin.py, tests/test_temp_directory.py
Also fixes that a cleanup message is printed while pytest-workflow was not used.
=> Display an error message when --basetemp is a subdirectory of pytest's CWD

HISTORY.rst, src/pytest_workflow/plugin.py, tests/test_workflow_dependent_tests.py
Prevents a pytest warning from occurring.
=> Add workflow marker to the config

HISTORY.rst, MANIFEST.in
This should solve #83. When creating a new source distribution with ``python setup.py sdist``, the LICENSE will now be included in the archive. Wheels were fine from the outset.
=> add manifest with license

HISTORY.rst, src/pytest_workflow/content_tests.py, src/pytest_workflow/file_tests.py, src/pytest_workflow/plugin.py, src/pytest_workflow/schema.py, src/pytest_workflow/workflow.py, tests/test_content_functions.py, tests/test_fail_messages.py, tests/test_file_functions.py, tests/test_miscellaneous_crashes.py, tests/test_multithreading.py, tests/test_schema.py, tests/test_temp_directory.py, tests/test_warnings.py, tests/test_workflow_queue.py
I have removed the file to string generator. A file handle is also a `Iterable[str]` type, so the content checking now iterates over the file handle itself. This is much faster as this file handle is implemented in C.
I also removed the length check of the sets before checking on equality. This was supposed to improve the speed, but in CPython this length check is already done before equality checking. CPython is of course much faster.
The same goes for removing the `found_strings` set from the `strings_to_check` set. If `found_strings` is empty, then this is detected very early in the algorithm and nothing is done to `strings_to_check`.
So it really helps to check the CPython implementation first before you make assumptions about speedy algorithms.
=> Refactor pytest-workflow using python 3.6 tools.

HISTORY.rst, README.rst, docs/known_issues.rst, docs/writing_tests.rst, src/pytest_workflow/content_tests.py, src/pytest_workflow/file_tests.py, src/pytest_workflow/schema.py, src/pytest_workflow/schema/schema.json, tests/test_content_functions.py, tests/test_fail_messages.py, tests/test_schema.py, tests/test_success_messages.py, tests/yamls/valid/.hidden_invalid_yaml, tests/yamls/valid/regex_file.yaml
This adds `contains_regex` and `must_not_contains_regex` to pytest-workflow, and resolves #106.
=> Add regex evaluation to the test possibilities.

HISTORY.rst, src/pytest_workflow/plugin.py, src/pytest_workflow/util.py, tests/test_temp_directory.py
These issues cropped up when using Cromwell to run some tasks with docker, where the tool needed to run as a certain user (root for example). That would leave on the filesystem that can not be removed by pytest-workflow. 
This made pytest-workflow stop with a non-zero exit code, even though all tests succeeded. It also printed a stacktrace at the end of the results. This should now be alleviated. A message will be printed that states which directories could not be removed.
=> Give more friendly errors on permission errors when trying to remove directories.

HISTORY.rst, docs/running_pytest_workflow.rst, src/pytest_workflow/plugin.py, src/pytest_workflow/util.py, tests/test_utils.py, tests/test_warnings.py
@DavyCats @Redmar-van-den-Berg , could you please review this? It should reduce the wear and tear on your SSDs significantly :wink:. 
Preliminary testing with Germline-DNA pipeline. Copying everything for all tests: 2.1 GB. Using `--git-aware` option: 460 MB. 
The .git folder contains a lot of cruft!
=> Make pytest-workflow git-aware

HISTORY.rst, setup.py, src/pytest_workflow/plugin.py, tests/functional/test_functional.py, tests/test_fail_messages.py, tests/test_miscellaneous_crashes.py, tests/test_multithreading.py, tests/test_success_messages.py, tests/test_tags.py, tests/test_temp_directory.py, tests/test_threading_errors.py, tests/test_warnings.py, tests/test_workflow_dependent_tests.py
Pytest is switching away from its own `Path` implementation, using `pathlib.Path` instead. This came with some deprecation warnings.
=> Fix deprecation warnings from pytest 7.0.0

HISTORY.rst, src/pytest_workflow/content_tests.py, src/pytest_workflow/file_tests.py, src/pytest_workflow/plugin.py, src/pytest_workflow/workflow.py, tests/test_fail_messages.py, tests/test_skip_tests.py, tests/test_workflow.py
=> Exitcode skips

HISTORY.rst, src/pytest_workflow/plugin.py, src/pytest_workflow/util.py, tests/test_miscellaneous_crashes.py, tests/test_utils.py
Fixes #167 
In the log given at that bug it shows that the progress bar of snakemake contains very large arrays of non-ASCII characters. This makes an error caused by stderr-bytes quite likely. Therefore I will create a new release after this is merged.
=> Fix crash when stderr bytes is not properly not aligned with the encoding

HISTORY.rst, docs/writing_tests.rst, requirements.txt, setup.py, src/pytest_workflow/file_tests.py, src/pytest_workflow/schema.py, src/pytest_workflow/schema/schema.json, src/pytest_workflow/util.py, tests/test_schema.py, tests/test_utils.py
I frequently have workflows that generate *.fastq.gz files as outputs. Because gzip embeds a timestamp in the file, md5sum comparisons fail. `gzip` with `-n` can be used to omit the timestamp, but the gzipping is often part of third-party tool and not configurable. This PR adds a `ungzip_md5sum` option that runs md5sum on the ungzipped contents of the file.
=> Add extract_md5sum check

HISTORY.rst, src/pytest_workflow/plugin.py
=> Make pytest_collect_file() compatible with pytest 8.1+

.github/workflows/ci.yml, HISTORY.rst, setup.py, src/pytest_workflow/plugin.py, tests/functional/simple_snakefile_test_cases.yml
=> Add 3.12 python support, drop 3.7 support

.github/workflows/ci.yml, .readthedocs.yml, HISTORY.rst, README.rst, docs/writing_tests.rst, requirements.txt, setup.py, src/pytest_workflow/file_tests.py, src/pytest_workflow/plugin.py, src/pytest_workflow/schema.py, src/pytest_workflow/schema/schema.json, src/pytest_workflow/util.py, tests/functional/simple_snakefile_test_cases.yml, tests/test_schema.py, tests/test_utils.py
=> Release 2.1.0
